"use client";
import {useCallback,useEffect,useRef,useState} from "react";
type P={x:number;y:number}; type Phase="title"|"playing"|"win"|"lose";
const items=[{id:"card",x:17,y:18,icon:"🪪",label:"タイムカード"},{id:"coat",x:78,y:17,icon:"🧥",label:"上着"},{id:"guts",x:50,y:52,icon:"🔥",label:"帰る勇気"}];
const desks=[[20,31],[35,31],[50,31],[65,31],[80,31],[27,44],[43,44],[59,44],[75,44]];
const barks=["あれ、もう帰るの？","5分だけいい？","今ちょっといいかな","熱意、見せてる？","このあと軽く会議ね","若いうちは量だよ","背中が帰宅してるぞ","定時は目安だよ？"];
const dist=(a:P,b:P)=>Math.hypot(a.x-b.x,a.y-b.y);
export default function Home(){
 const [phase,setPhase]=useState<Phase>("title"),[player,setPlayer]=useState<P>({x:8,y:57}),[boss,setBoss]=useState<P>({x:52,y:12}),[got,setGot]=useState<string[]>([]),[time,setTime]=useState(60),[pressure,setPressure]=useState(0),[score,setScore]=useState(0),[bark,setBark]=useState("部長は企画書を読んでいる…今だ！"),[flash,setFlash]=useState("");
 const keys=useRef(new Set<string>()),pr=useRef(player),gr=useRef(got),xr=useRef(pressure),bd=useRef<P>({x:1,y:.25}),tick=useRef(0);
 useEffect(()=>{pr.current=player},[player]);useEffect(()=>{gr.current=got},[got]);useEffect(()=>{xr.current=pressure},[pressure]);
 const reset=useCallback(()=>{setPlayer({x:8,y:57});setBoss({x:52,y:12});setGot([]);setTime(60);setPressure(0);setScore(0);setFlash("");setBark("部長は企画書を読んでいる…今だ！");tick.current=0;setPhase("playing")},[]);
 useEffect(()=>{const dn=(e:KeyboardEvent)=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();keys.current.add(e.key.toLowerCase());if(phase!=="playing"&&(e.key===" "||e.key==="Enter"))reset()},up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener("keydown",dn);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",dn);window.removeEventListener("keyup",up)}},[phase,reset]);
 useEffect(()=>{if(phase!=="playing")return;const t=setInterval(()=>setTime(v=>{if(v<=1){setPhase("lose");setBark("終電？会社で寝ればいいじゃない");return 0}return v-1}),1000);return()=>clearInterval(t)},[phase]);
 useEffect(()=>{if(phase!=="playing")return;const loop=setInterval(()=>{tick.current++;const k=keys.current;let dx=+(k.has("arrowright")||k.has("d"))-+(k.has("arrowleft")||k.has("a")),dy=+(k.has("arrowdown")||k.has("s"))-+(k.has("arrowup")||k.has("w"));if(dx||dy){const l=Math.hypot(dx,dy);dx/=l;dy/=l}const n={x:Math.max(3,Math.min(96,pr.current.x+dx*1.15)),y:Math.max(7,Math.min(61,pr.current.y+dy*1.15))};if(!desks.some(([x,y])=>Math.abs(n.x-x)<5.5&&Math.abs(n.y-y)<4.3)){pr.current=n;setPlayer(n)}setBoss(o=>{const chase=dist(o,pr.current)<23;let vx=chase?pr.current.x-o.x:bd.current.x,vy=chase?pr.current.y-o.y:bd.current.y,l=Math.hypot(vx,vy)||1;vx/=l;vy/=l;let q={x:o.x+vx*(chase?.68:.36),y:o.y+vy*(chase?.68:.36)};if(q.x<7||q.x>92){bd.current.x*=-1;q.x=Math.max(7,Math.min(92,q.x))}if(q.y<9||q.y>57){bd.current.y*=-1;q.y=Math.max(9,Math.min(57,q.y))}const seen=dist(q,pr.current)<16,p=Math.max(0,Math.min(100,xr.current+(seen?3.4:-1.35)));xr.current=p;setPressure(p);if(seen&&tick.current%28===0)setBark(barks[Math.floor(Math.random()*barks.length)]);if(p>=100){setPhase("lose");setBark("捕まえた！今から議事録お願い")}return q});for(const it of items)if(!gr.current.includes(it.id)&&dist(pr.current,it)<5){const u=[...gr.current,it.id];gr.current=u;setGot(u);setScore(s=>s+1000+Math.round(time*10));setFlash(`${it.icon} ${it.label} GET!`);setTimeout(()=>setFlash(""),900)}if(gr.current.length===3&&pr.current.x>88&&pr.current.y>51){setScore(s=>s+Math.round(time*100)+Math.round((100-xr.current)*30));setPhase("win")}},34);return()=>clearInterval(loop)},[phase,time]);
 const hold=(k:string,on:boolean)=>on?keys.current.add(k):keys.current.delete(k),rank=score>9500?"伝説の帰宅神":score>6500?"定時の貴公子":"そこそこ社員";
 return <main className="shell"><header><div className="brand"><span>定時</span>ダッシュ<span className="stamp">極</span></div><div className="mission">MISSION: 部長にバレずに帰れ</div></header>
 <section className="hud"><div><small>退勤まで</small><strong className={time<11?"danger":""}>{String(time).padStart(2,"0")}<i>秒</i></strong></div><div className="items"><small>帰宅セット</small><span>{items.map(p=><b key={p.id} className={got.includes(p.id)?"got":""}>{p.icon}</b>)}</span></div><div className="pressure"><small>部長の圧</small><div><i style={{width:`${pressure}%`}}/></div></div><div className="score"><small>査定(仮)</small><strong>{score.toLocaleString()}</strong></div></section>
 <section className="game"><div className="floor-lines"/><div className="room-label kitchen">給湯室</div><div className="room-label meeting">無限会議室</div>{desks.map(([x,y],i)=><div className="desk" key={i} style={{left:`${x}%`,top:`${y}%`}}><span>{i%3===0?"☕":"▤"}</span></div>)}<div className={`elevator ${got.length===3?"open":""}`}><span>▲</span><b>脱出口</b><small>{got.length===3?"OPEN":`${3-got.length}個不足`}</small></div>{items.map(p=>!got.includes(p.id)&&<div className="pickup" key={p.id} style={{left:`${p.x}%`,top:`${p.y}%`}}><span>{p.icon}</span><small>{p.label}</small></div>)}<div className="boss-zone" style={{left:`${boss.x}%`,top:`${boss.y}%`}}/><div className="character boss" style={{left:`${boss.x}%`,top:`${boss.y}%`}}><div className="speech">{bark}</div><span>👹</span><b>部長</b></div><div className="character player" style={{left:`${player.x}%`,top:`${player.y}%`}}><span>🏃</span><b>あなた</b></div>{flash&&<div className="flash">{flash}</div>}
 {phase!=="playing"&&<div className="overlay">{phase==="title"&&<><div className="eyebrow">働き方改革ステルスアクション</div><h1>定時になった。<br/><em>帰るだけなのに、命がけ。</em></h1><p>3つの帰宅セットを回収し、部長の「ちょっといい？」から逃げ切れ。</p><button onClick={reset}>退勤を試みる <kbd>SPACE</kbd></button><div className="how"><span>⌨️ WASD / 矢印で移動</span><span>📱 下のボタンでも移動</span></div></>}{phase==="win"&&<><div className="result-icon">🎉</div><h1>退勤成功！</h1><p>あなたは会社という名のダンジョンを脱出した。</p><div className="result"><span>{rank}</span><strong>{score.toLocaleString()}<small>点</small></strong></div><button onClick={reset}>もう一度、帰る</button></>}{phase==="lose"&&<><div className="result-icon">📋</div><h1>退勤失敗…</h1><p>部長「ちょうどよかった。資料、明朝までね」</p><div className="overtime">残業 +3時間</div><button onClick={reset}>時を戻す</button></>}</div>}</section>
 <nav className="controls">{[["↑","arrowup"],["←","arrowleft"],["↓","arrowdown"],["→","arrowright"]].map(([v,k])=><button key={k} aria-label={v} onPointerDown={()=>hold(k,true)} onPointerUp={()=>hold(k,false)} onPointerLeave={()=>hold(k,false)}>{v}</button>)}</nav><footer><span>※本ゲームはフィクションです。たぶん。</span><b>音量 0%（心の叫びは最大）</b></footer></main>}
